### ISSUE TITLE
use dot env and hide ur password from public repos

### ISSUE THREAD

**Issue by shubham8550** [shanky1947/Dossier-Portfolio-Website-Generator#1]
https://github.com/shanky1947/Dossier-Portfolio-Website-Generator/blob/master/main/config.txt

thats definitely not good idea to even put ur old passwords

**Comment by shanky1947** [comment]
Thanks @shubham8550 , removed the same.

**Comment by shubham8550** [comment]
np, 

tip: [Here](https://github.com/shanky1947/Dossier-Portfolio-Website-Generator/blob/cab09fcc51f146b3c4fa175ec1ade36f6c325a81/main/linkedin_scraper.py#L26C2-L29C24)  you generally use dotenv [for python](https://pypi.org/project/python-dotenv/)  it does same thing but kind of standard practice in most of programming world

you can have
.gitignore with ".env" in it   (so you can put your secrets in .env and it won't be tracked by git )
and
.env.example file for others to refer
